name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python
      - name: black lint
        run: |
          python -m pip install black
          black . --check --line-length 120
